### ISSUE TITLE
Request for Smart Charging using OCPP

### ISSUE THREAD

**Issue by ace-roger** [heroyooki/ocpp-csms-backend#3]
Hi heroyooki,

Awesome Project - I am going through your videos 
Fewer videos are on the practical implementation of OCPP, which also end to end.
Thank you.

I was looking to enable smart charging using OCPP by using charging profiles.

https://www.ampcontrol.io/post/how-to-send-ev-charging-profiles-to-your-open-charge-point-protocol-ocpp-charging-station

Your guidance will be greatly appreciated.

**Comment by ace-roger** [comment]
Refrence:

https://www.ampcontrol.io/ocpp-guide/how-to-use-smart-charging-with-ocpp

**Comment by heroyooki** [comment]
Hello! Thanks for watching. I moved the project into the https://github.com/heroyooki/ocpp-fastapi-vue3.
Regarding your reference, I gonna investigate this, thank you.
